// Comprehensive list of major Indian cities & metropolitan hubs
export const INDIAN_CITIES = [
  'Kolkata',
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Chennai',
  'Pune',
  'Ahmedabad',
  'Jaipur',
  'Chandigarh',
  'Lucknow',
  'Indore',
  'Surat',
  'Kochi',
  'Goa',
  'Nagpur',
  'Bhopal',
  'Patna',
  'Vadodara',
  'Coimbatore',
  'Visakhapatnam',
  'Bhubaneswar',
  'Guwahati',
  'Varanasi',
  'Dehradun',
  'Amritsar',
  'Agra',
  'Kanpur',
  'Ludhiana',
  'Ranchi',
  'Mysore',
  'Noida',
  'Gurgaon',
  'Srinagar',
  'Kozhikode',
  'Mangalore',
  'Thiruvananthapuram',
  'Raipur',
  'Jodhpur',
  'Udaipur'
];

export const CITIES_METADATA = [
  // Indian Metro & Major Cities
  { name: 'Kolkata', country: 'India', flag: '🇮🇳', region: 'West Bengal' },
  { name: 'Mumbai', country: 'India', flag: '🇮🇳', region: 'Maharashtra' },
  { name: 'Delhi', country: 'India', flag: '🇮🇳', region: 'Delhi NCR' },
  { name: 'Bangalore', country: 'India', flag: '🇮🇳', region: 'Karnataka' },
  { name: 'Hyderabad', country: 'India', flag: '🇮🇳', region: 'Telangana' },
  { name: 'Chennai', country: 'India', flag: '🇮🇳', region: 'Tamil Nadu' },
  { name: 'Pune', country: 'India', flag: '🇮🇳', region: 'Maharashtra' },
  { name: 'Ahmedabad', country: 'India', flag: '🇮🇳', region: 'Gujarat' },
  { name: 'Jaipur', country: 'India', flag: '🇮🇳', region: 'Rajasthan' },
  { name: 'Chandigarh', country: 'India', flag: '🇮🇳', region: 'Punjab/Haryana' },
  { name: 'Lucknow', country: 'India', flag: '🇮🇳', region: 'Uttar Pradesh' },
  { name: 'Indore', country: 'India', flag: '🇮🇳', region: 'Madhya Pradesh' },
  { name: 'Surat', country: 'India', flag: '🇮🇳', region: 'Gujarat' },
  { name: 'Kochi', country: 'India', flag: '🇮🇳', region: 'Kerala' },
  { name: 'Goa', country: 'India', flag: '🇮🇳', region: 'Goa' },
  { name: 'Nagpur', country: 'India', flag: '🇮🇳', region: 'Maharashtra' },
  { name: 'Bhopal', country: 'India', flag: '🇮🇳', region: 'Madhya Pradesh' },
  { name: 'Patna', country: 'India', flag: '🇮🇳', region: 'Bihar' },
  { name: 'Vadodara', country: 'India', flag: '🇮🇳', region: 'Gujarat' },
  { name: 'Coimbatore', country: 'India', flag: '🇮🇳', region: 'Tamil Nadu' },
  { name: 'Visakhapatnam', country: 'India', flag: '🇮🇳', region: 'Andhra Pradesh' },
  { name: 'Bhubaneswar', country: 'India', flag: '🇮🇳', region: 'Odisha' },
  { name: 'Guwahati', country: 'India', flag: '🇮🇳', region: 'Assam' },
  { name: 'Varanasi', country: 'India', flag: '🇮🇳', region: 'Uttar Pradesh' },
  { name: 'Dehradun', country: 'India', flag: '🇮🇳', region: 'Uttarakhand' },
  { name: 'Amritsar', country: 'India', flag: '🇮🇳', region: 'Punjab' },
  { name: 'Agra', country: 'India', flag: '🇮🇳', region: 'Uttar Pradesh' },
  { name: 'Kanpur', country: 'India', flag: '🇮🇳', region: 'Uttar Pradesh' },
  { name: 'Ludhiana', country: 'India', flag: '🇮🇳', region: 'Punjab' },
  { name: 'Ranchi', country: 'India', flag: '🇮🇳', region: 'Jharkhand' },
  { name: 'Mysore', country: 'India', flag: '🇮🇳', region: 'Karnataka' },
  { name: 'Noida', country: 'India', flag: '🇮🇳', region: 'Uttar Pradesh' },
  { name: 'Gurgaon', country: 'India', flag: '🇮🇳', region: 'Haryana' },
  { name: 'Srinagar', country: 'India', flag: '🇮🇳', region: 'Jammu & Kashmir' },
  { name: 'Kozhikode', country: 'India', flag: '🇮🇳', region: 'Kerala' },
  { name: 'Mangalore', country: 'India', flag: '🇮🇳', region: 'Karnataka' },
  { name: 'Thiruvananthapuram', country: 'India', flag: '🇮🇳', region: 'Kerala' },
  { name: 'Raipur', country: 'India', flag: '🇮🇳', region: 'Chhattisgarh' },
  { name: 'Jodhpur', country: 'India', flag: '🇮🇳', region: 'Rajasthan' },
  { name: 'Udaipur', country: 'India', flag: '🇮🇳', region: 'Rajasthan' },

  // Global Fashion & Techwear Hubs
  { name: 'Tokyo', country: 'Japan', flag: '🇯🇵', region: 'Kanto' },
  { name: 'Seoul', country: 'South Korea', flag: '🇰🇷', region: 'Gyeonggi' },
  { name: 'London', country: 'United Kingdom', flag: '🇬🇧', region: 'England' },
  { name: 'New York', country: 'United States', flag: '🇺🇸', region: 'New York' },
  { name: 'Seattle', country: 'United States', flag: '🇺🇸', region: 'Washington' },
  { name: 'Berlin', country: 'Germany', flag: '🇩🇪', region: 'Berlin' },
  { name: 'Paris', country: 'France', flag: '🇫🇷', region: 'Île-de-France' },
  { name: 'Los Angeles', country: 'United States', flag: '🇺🇸', region: 'California' }
];

export const normalizeCityName = (cityName) => {
  if (!cityName) return 'Kolkata';
  const trimmed = cityName.trim();
  if (trimmed.toLowerCase() === 'delhi ncr') return 'Delhi';
  return trimmed;
};
